version: '3'

services:
    server:
        container_name: server
        build:
            context: .
        env_file:
            - ./.development.env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 5000:5000
            - 9229:9229
        command: npm run start:dev
        depends_on:
            - db
        restart: always
    db:
        container_name: db
        image: postgres
        restart: always
        env_file:
            - ./.development.env
        environment:
            PG_DATA: /var/lib/postgresql/data
        ports:
            - 54321:5432
        volumes:
            - dbdata:/var/lib/postgresql/data
        restart: always

volumes:
    dbdata:
